# Generated by Django 4.2 on 2023-11-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='my_custom_user_table',
        ),
    ]
